//
//  OGSMainTabBarViewController.swift
//  iosgo
//
//  Created by Cheese Onhead on 5/27/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSMainTabBarViewControllerInput
{
    func displayscene(viewModel: OGSMainTabBar.loadscene.ViewModel)
}

protocol OGSMainTabBarViewControllerOutput
{
    func doSomething(request: OGSMainTabBar.loadscene.Request)
}

protocol OGSMainTabBarViewControllerRouter: Router {}

class OGSMainTabBarViewController: UIViewController, OGSMainTabBarViewControllerInput
{
    var output: OGSMainTabBarViewControllerOutput!
    var router: OGSMainTabBarViewControllerRouter!

    // MARK: - Object lifecycle

    override func awakeFromNib()
    {
        super.awakeFromNib()
        OGSMainTabBarConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }

    // MARK: - Event handling

    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work

        let request = OGSMainTabBar.loadscene.Request()
        output.doSomething(request: request)
    }

    // MARK: - Display logic

    func displayscene(viewModel _: OGSMainTabBar.loadscene.ViewModel)
    {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}
