//
//  OGSMainTabBarConfigurator.swift
//  iosgo
//
//  Created by Cheese Onhead on 5/27/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class OGSMainTabBarConfigurator
{
    static let sharedInstance = OGSMainTabBarConfigurator()

    private init() {}

    func configure(viewController: OGSMainTabBarViewController)
    {
        let presenter = OGSMainTabBarPresenter()
        presenter.output = viewController

        let interactor = OGSMainTabBarInteractor()
        interactor.output = presenter

        let router = OGSMainTabBarRouter(viewController: viewController, dataProvider: interactor, dataReceiver: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}

extension OGSMainTabBarViewController: OGSMainTabBarPresenterOutput
{
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        router.passDataToNextScene(for: segue)
    }
}

extension OGSMainTabBarInteractor: OGSMainTabBarViewControllerOutput, OGSMainTabBarRouterDataProvider, OGSMainTabBarRouterDataReceiver {}

extension OGSMainTabBarPresenter: OGSMainTabBarInteractorOutput {}

extension OGSMainTabBarRouter: OGSMainTabBarViewControllerRouter {}
