//
//  OGSMainTabBarRouter.swift
//  iosgo
//
//  Created by Cheese Onhead on 5/27/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSMainTabBarRouterInput
{
    func navigateToSomewhere()
}

protocol OGSMainTabBarRouterDataProvider: class {}

protocol OGSMainTabBarRouterDataReceiver: class {}

class OGSMainTabBarRouter: OGSMainTabBarRouterInput
{
    weak var viewController: UIViewController!
    private weak var dataProvider: OGSMainTabBarRouterDataProvider!
    weak var dataReceiver: OGSMainTabBarRouterDataReceiver!

    init(viewController: UIViewController, dataProvider: OGSMainTabBarRouterDataProvider, dataReceiver: OGSMainTabBarRouterDataReceiver)
    {
        self.viewController = viewController
        self.dataProvider = dataProvider
        self.dataReceiver = dataReceiver
    }

    // MARK: - Navigation

    func navigateToSomewhere()
    {
        // NOTE: Teach the router how to navigate to another scene. Some examples follow:

        // 1. Trigger a storyboard segue
        // viewController.performSegueWithIdentifier("ShowSomewhereScene", sender: nil)

        // 2. Present another view controller programmatically
        // viewController.presentViewController(someWhereViewController, animated: true, completion: nil)

        // 3. Ask the navigation controller to push another view controller onto the stack
        // viewController.navigationController?.pushViewController(someWhereViewController, animated: true)

        // 4. Present a view controller from a different storyboard
        // let storyboard = UIStoryboard(name: "OtherThanMain", bundle: nil)
        // let someWhereViewController = storyboard.instantiateInitialViewController() as! SomeWhereViewController
        // viewController.navigationController?.pushViewController(someWhereViewController, animated: true)
    }

    // MARK: - Communication

    func passDataToNextScene(for segue: UIStoryboardSegue)
    {
        // NOTE: Teach the router which scenes it can communicate with

        if segue.identifier == "ShowSomewhereScene"
        {
            passDataToSomewhereScene(segue: segue)
        }
    }

    func passDataToSomewhereScene(segue _: UIStoryboardSegue)
    {
        // NOTE: Teach the router how to pass data to the next scene

        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
