//
//  OGSMainTabBarInteractor.swift
//  iosgo
//
//  Created by Cheese Onhead on 5/27/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSMainTabBarInteractorInput
{
    func doSomething(request: OGSMainTabBar.loadscene.Request)
}

protocol OGSMainTabBarInteractorOutput
{
    func presentscene(response: OGSMainTabBar.loadscene.Response)
}

class OGSMainTabBarInteractor: OGSMainTabBarInteractorInput
{
    var output: OGSMainTabBarInteractorOutput!

    // MARK: - Business logic

    func doSomething(request _: OGSMainTabBar.loadscene.Request)
    {
        // NOTE: Create some Worker to do the work

        // NOTE: Pass the result to the Presenter

        let response = OGSMainTabBar.loadscene.Response()
        output.presentscene(response: response)
    }
}
