//
//  OGSMainTabBarViewController.swift
//  iosgo
//
//  Created by Cheese Onhead on 5/27/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSMainTabBarControllerInput
{
    func displayScene(viewModel: OGSMainTabBar.loadScene.ViewModel)
}

protocol OGSMainTabBarControllerOutput
{
    func loadScene(request: OGSMainTabBar.loadScene.Request)
}

class OGSMainTabBarController: UITabBarController, OGSMainTabBarControllerInput
{
    var output: OGSMainTabBarControllerOutput!
    var router: OGSMainTabBarRouter!

    // MARK: - Object lifecycle

    override func awakeFromNib()
    {
        super.awakeFromNib()
        OGSMainTabBarConfigurator.sharedInstance.configure(viewController: self)
    }

    func displayScene(viewModel _: OGSMainTabBar.loadScene.ViewModel)
    {
    }
}
