//
//  OGSMainTabBarPresenter.swift
//  iosgo
//
//  Created by Cheese Onhead on 5/27/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSMainTabBarPresenterInput
{
    func presentscene(response: OGSMainTabBar.loadscene.Response)
}

protocol OGSMainTabBarPresenterOutput: class
{
    func displayscene(viewModel: OGSMainTabBar.loadscene.ViewModel)
}

class OGSMainTabBarPresenter: OGSMainTabBarPresenterInput
{
    weak var output: OGSMainTabBarPresenterOutput!

    // MARK: - Presentation logic

    func presentscene(response _: OGSMainTabBar.loadscene.Response)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = OGSMainTabBar.loadscene.ViewModel()
        output.displayscene(viewModel: viewModel)
    }
}
