//
//  SplashModels.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/4/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Splash
{
    struct LoadScene
    {
        struct Request
        {
        }

        struct Response
        {
            var loggedIn: Bool
        }

        struct ViewModel
        {
            var nextSceneType: NextSceneType

            enum NextSceneType
            {
                case login
                case lobby
            }
        }
    }
}
