//
//  OGSLoginConfigurator.swift
//  iosgo
//
//  Created by Jeffrey Wu on 2017-02-15.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class OGSLoginConfigurator
{
    static let sharedInstance = OGSLoginConfigurator()

    private init() {}

    func configure(viewController: OGSLoginViewController)
    {
        let presenter = OGSLoginPresenter()
        presenter.output = viewController

        let interactor = OGSLoginInteractor()
        interactor.output = presenter

        let router = OGSLoginRouter(viewController: viewController, dataProvider: interactor, dataReceiver: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}

extension OGSLoginViewController: OGSLoginPresenterOutput {}

extension OGSLoginInteractor: OGSLoginViewControllerOutput, OGSLoginRouterDataProvider, OGSLoginRouterDataReceiver {}

extension OGSLoginPresenter: OGSLoginInteractorOutput {}
