//
//  OGSLoginViewController.swift
//  iosgo
//
//  Created by Jeffrey Wu on 2017-02-15.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSLoginViewControllerInput
{
    func displayLogin(viewModel: OGSLogin.Login.ViewModel)
}

protocol OGSLoginViewControllerOutput
{
    func doSomething(request: OGSLogin.Login.Request)
}

protocol OGSLoginViewControllerRouter {}

class OGSLoginViewController: UIViewController, OGSLoginViewControllerInput
{
    // MARK: - Views
    @IBOutlet weak var usernameTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    @IBOutlet weak var loginButton: UIButton!

    var output: OGSLoginViewControllerOutput!
    var router: OGSLoginViewControllerRouter!

    // MARK: - Lifecycle

    override func awakeFromNib()
    {
        super.awakeFromNib()
        OGSLoginConfigurator.sharedInstance.configure(viewController: self)
    }

    func displayLogin(viewModel _: OGSLogin.Login.ViewModel)
    {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}
