//
//  OGSLoginPresenter.swift
//  iosgo
//
//  Created by Jeffrey Wu on 2017-02-15.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSLoginPresenterInput
{
    func presentLogin(response: OGSLogin.Login.Response)
}

protocol OGSLoginPresenterOutput: class
{
    func displayLogin(viewModel: OGSLogin.Login.ViewModel)
}

class OGSLoginPresenter: OGSLoginPresenterInput
{
    weak var output: OGSLoginPresenterOutput!

    // MARK: - Presentation logic

    func presentLogin(response _: OGSLogin.Login.Response)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = OGSLogin.Login.ViewModel(readyToNavigate: false, userInputState: .pending, errorLabelHidden: true, errorLabelMessage: nil)
        output.displayLogin(viewModel: viewModel)
    }
}
