//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___PresenterInput
{
}

protocol ___VARIABLE_sceneName___PresenterOutput: class
{
}

class ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresenterInput
{
    weak var output: ___VARIABLE_sceneName___PresenterOutput!
}
