//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ___FILEBASENAMEASIDENTIFIER___RouterInput {}

protocol ___FILEBASENAMEASIDENTIFIER___RouterDataProvider: class {}

protocol ___FILEBASENAMEASIDENTIFIER___RouterDataReceiver: class {}

class ___FILEBASENAMEASIDENTIFIER___Router: ___FILEBASENAMEASIDENTIFIER___RouterInput
{
    weak var viewController: UIViewController!
    private weak var dataProvider: ___FILEBASENAMEASIDENTIFIER___RouterDataProvider!
    weak var dataReceiver: ___FILEBASENAMEASIDENTIFIER___RouterDataReceiver!

    init(viewController: UIViewController, dataProvider: ___FILEBASENAMEASIDENTIFIER___RouterDataProvider, dataReceiver: ___FILEBASENAMEASIDENTIFIER___RouterDataReceiver)
    {
        self.viewController = viewController
        self.dataProvider = dataProvider
        self.dataReceiver = dataReceiver
    }
}
