//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ___VARIABLE_sceneName___Configurator
{
    static func configure(viewController: ___VARIABLE_sceneName___ViewController)
    {
        let presenter = ___VARIABLE_sceneName___Presenter()
        presenter.output = viewController

        let interactor = ___VARIABLE_sceneName___Interactor()
        interactor.output = presenter

        let router = ___VARIABLE_sceneName___Router(viewController: viewController, dataProvider: interactor, dataReceiver: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}

extension ___VARIABLE_sceneName___ViewController: ___VARIABLE_sceneName___PresenterOutput {}

extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___ViewControllerOutput, ___VARIABLE_sceneName___RouterDataProvider, ___VARIABLE_sceneName___RouterDataReceiver {}

extension ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___InteractorOutput {}
