//
//  OGSChooseGamePresenter.swift
//  iosgo
//
//  Created by Jeffrey Wu on 2017-02-26.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSChooseGamePresenterInput
{
    func presenta(response: OGSChooseGame.aa.Response)
}

protocol OGSChooseGamePresenterOutput: class
{
    func displaya(viewModel: OGSChooseGame.aa.ViewModel)
}

class OGSChooseGamePresenter: OGSChooseGamePresenterInput
{
    weak var output: OGSChooseGamePresenterOutput!

    // MARK: - Presentation logic

    func presenta(response _: OGSChooseGame.aa.Response)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let viewModel = OGSChooseGame.aa.ViewModel()
        output.displaya(viewModel: viewModel)
    }
}
