//
//  OGSChooseGameRouter.swift
//  iosgo
//
//  Created by Jeffrey Wu on 2017-02-26.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSChooseGameRouterInput
{
    func navigateToChallenge()
}

protocol OGSChooseGameRouterDataProvider: class
{
    var selectedGame: OGSChallenge? { get }
}

protocol OGSChooseGameRouterDataReceiver: class {}

class OGSChooseGameRouter: OGSChooseGameRouterInput
{
    weak var viewController: UIViewController!
    private weak var dataProvider: OGSChooseGameRouterDataProvider!
    weak var dataReceiver: OGSChooseGameRouterDataReceiver!

    init(viewController: UIViewController, dataProvider: OGSChooseGameRouterDataProvider, dataReceiver: OGSChooseGameRouterDataReceiver)
    {
        self.viewController = viewController
        self.dataProvider = dataProvider
        self.dataReceiver = dataReceiver
    }

    func navigateToChallenge()
    {
        print("Playing game!")
    }
}
