//
//  OGSChooseGameViewController.swift
//  iosgo
//
//  Created by Jeffrey Wu on 2017-02-26.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSChooseGameViewControllerInput
{
    func displaya(viewModel: OGSChooseGame.aa.ViewModel)
}

protocol OGSChooseGameViewControllerOutput
{
    func doSomething(request: OGSChooseGame.aa.Request)
}

protocol OGSChooseGameViewControllerRouter: Router {}

class OGSChooseGameViewController: UIViewController, OGSChooseGameViewControllerInput
{
    var output: OGSChooseGameViewControllerOutput!
    var router: OGSChooseGameViewControllerRouter!

    // MARK: - Object lifecycle

    override func awakeFromNib()
    {
        super.awakeFromNib()
        OGSChooseGameConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }

    // MARK: - Event handling

    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work

        let request = OGSChooseGame.aa.Request()
        output.doSomething(request: request)
    }

    // MARK: - Display logic

    func displaya(viewModel _: OGSChooseGame.aa.ViewModel)
    {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}
