//
//  OGSChooseGameConfigurator.swift
//  iosgo
//
//  Created by Jeffrey Wu on 2017-02-26.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class OGSChooseGameConfigurator
{
    static let sharedInstance = OGSChooseGameConfigurator()

    private init() {}

    func configure(viewController: OGSChooseGameViewController)
    {
        let presenter = OGSChooseGamePresenter()
        presenter.output = viewController

        let interactor = OGSChooseGameInteractor()
        interactor.output = presenter

        let router = OGSChooseGameRouter(viewController: viewController, dataProvider: interactor, dataReceiver: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}

extension OGSChooseGameViewController: OGSChooseGamePresenterOutput
{
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        router.passDataToNextScene(for: segue)
    }
}

extension OGSChooseGameInteractor: OGSChooseGameViewControllerOutput, OGSChooseGameRouterDataProvider, OGSChooseGameRouterDataReceiver {}

extension OGSChooseGamePresenter: OGSChooseGameInteractorOutput {}
