//
//  OGSChooseGameInteractor.swift
//  iosgo
//
//  Created by Jeffrey Wu on 2017-02-26.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol OGSChooseGameInteractorInput
{
    func doSomething(request: OGSChooseGame.aa.Request)
}

protocol OGSChooseGameInteractorOutput
{
    func presenta(response: OGSChooseGame.aa.Response)
}

class OGSChooseGameInteractor: OGSChooseGameInteractorInput
{
    var output: OGSChooseGameInteractorOutput!

    // MARK: - Business logic

    func doSomething(request _: OGSChooseGame.aa.Request)
    {
        // NOTE: Create some Worker to do the work

        // NOTE: Pass the result to the Presenter

        let response = OGSChooseGame.aa.Response()
        output.presenta(response: response)
    }
}
