//
//  PlayRouter.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/18/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PlayRouterRouterInput {}

protocol PlayRouterRouterDataProvider: class {}

protocol PlayRouterRouterDataReceiver: class {}

class PlayRouterRouter: PlayRouterRouterInput {
    weak var viewController: UIViewController!
    private weak var dataProvider: PlayRouterRouterDataProvider!
    weak var dataReceiver: PlayRouterRouterDataReceiver!

    init(viewController: UIViewController, dataProvider: PlayRouterRouterDataProvider, dataReceiver: PlayRouterRouterDataReceiver) {
        self.viewController = viewController
        self.dataProvider = dataProvider
        self.dataReceiver = dataReceiver
    }
}
