//
//  PlayInteractor.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/25/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlayBusinessLogic {
    func loadScene(request: Play.LoadScene.Request)
}

class PlayInteractor: PlayBusinessLogic, PlayDataStore {

    var presenter: PlayPresentationLogic?
    var worker: PlayWorker?

    func loadScene(request _: Play.LoadScene.Request) {
        presenter?.presentLoadScene(response: Play.LoadScene.Response(stones: [Stone(type: .black, point: GridPoint(row: 1, col: 1)),
                                                                               Stone(type: .white, point: GridPoint(row: 2, col: 2))]))
    }
}
