//
//  PlayConfigurator.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/18/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class PlayConfiguratorConfigurator {
    static func configure(viewController: PlayConfiguratorViewController) {
        let presenter = PlayConfiguratorPresenter()
        presenter.output = viewController

        let interactor = PlayConfiguratorInteractor()
        interactor.output = presenter

        let router = PlayConfiguratorRouter(viewController: viewController, dataProvider: interactor, dataReceiver: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}

extension PlayConfiguratorViewController: PlayConfiguratorPresenterOutput {}

extension PlayConfiguratorInteractor: PlayConfiguratorViewControllerOutput, PlayConfiguratorRouterDataProvider, PlayConfiguratorRouterDataReceiver {}

extension PlayConfiguratorPresenter: PlayConfiguratorInteractorOutput {}
