//
//  PlayPresenter.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/18/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PlayPresenterPresenterInput {
}

protocol PlayPresenterPresenterOutput: class {
}

class PlayPresenterPresenter: PlayPresenterPresenterInput {
    weak var output: PlayPresenterPresenterOutput!
}
