//
//  PlayConfigurator.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/18/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class PlayConfigurator {
    static func configure(viewController: PlayViewController) {
        let presenter = PlayPresenter()
        presenter.output = viewController

        let interactor = PlayInteractor()
        interactor.output = presenter

        let router = PlayRouter(viewController: viewController, dataProvider: interactor, dataReceiver: interactor)

        viewController.output = interactor
        viewController.router = router
    }
}

extension PlayViewController: PlayPresenterOutput {}

extension PlayInteractor: PlayViewControllerOutput, PlayRouterDataProvider, PlayRouterDataReceiver {}

extension PlayPresenter: PlayInteractorOutput {}
