//
//  PlayPresenter.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/25/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlayPresentationLogic {
    func presentLoadScene(response: Play.LoadScene.Response)
}

class PlayPresenter: PlayPresentationLogic {

    weak var viewController: PlayDisplayLogic?

    func presentLoadScene(response _: Play.LoadScene.Response) {
        let model = Play.LoadScene.ViewModel(stones: [])
        viewController?.displayLoadScene(viewModel: model)
    }
}
