//
//  PlayRouter.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/18/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PlayRouterInput {}

protocol PlayRouterDataProvider: class {}

protocol PlayRouterDataReceiver: class {}

class PlayRouter: PlayRouterInput {
    weak var viewController: UIViewController!
    private weak var dataProvider: PlayRouterDataProvider!
    weak var dataReceiver: PlayRouterDataReceiver!

    init(viewController: UIViewController, dataProvider: PlayRouterDataProvider, dataReceiver: PlayRouterDataReceiver) {
        self.viewController = viewController
        self.dataProvider = dataProvider
        self.dataReceiver = dataReceiver
    }
}
