//
//  PlayPresenter.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/25/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlayPresentationLogic {
    func presentLoadScene(response: Play.LoadGame.Response)
}

class PlayPresenter: PlayPresentationLogic {

    weak var viewController: PlayDisplayLogic?

    private var renderer = GameRenderer()

    func presentLoadScene(response: Play.LoadGame.Response) {

        let state = renderer.getState(from: response.state)

        let model = Play.LoadGame.ViewModel(state: state)
        viewController?.displayLoadScene(viewModel: model)
    }
}
