//
//  PlayViewController.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/18/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SpriteKit

protocol PlayViewControllerInput {}

protocol PlayViewControllerOutput {}

class PlayViewController: UIViewController, PlayViewControllerInput {
    var output: PlayViewControllerOutput!
    var router: PlayRouter!

    @IBOutlet weak var boardView: SKView!

    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        PlayConfigurator.configure(viewController: self)
    }

    override func viewDidLoad() {
        // Load the SKScene from 'GameScene.sks'
        if let scene = SKScene(fileNamed: "BoardScene") {
            // Set the scale mode to scale to fit the window
            scene.scaleMode = .aspectFit

            // Present the scene
            boardView.presentScene(scene)
        }

        boardView.ignoresSiblingOrder = true

        boardView.showsFPS = true
        boardView.showsNodeCount = true
    }
}
