//
//  PlayViewController.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/25/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import SpriteKit
import UIKit

protocol PlayDisplayLogic: class {
    func displayLoadScene(viewModel: Play.LoadGame.ViewModel)
    func displayUpdateGame(viewModel: Play.UpdateGame.ViewModel)
}

class PlayViewController: UIViewController {
    var interactor: PlayBusinessLogic?
    var router: (NSObjectProtocol & PlayRoutingLogic & PlayDataPassing)?

    @IBOutlet var boardView: SKView!
    @IBOutlet var gameInfoView: GameInfoView!

    var boardScene: BoardScene!

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    override func viewDidLoad() {
        // Load the SKScene from 'GameScene.sks'
        if let scene = SKScene(fileNamed: "BoardScene") as? BoardScene {
            boardScene = scene

            // Set the scale mode to scale to fit the window
            boardScene.scaleMode = .aspectFit
            boardScene.actionDelegate = self

            // Present the scene
            boardView.presentScene(boardScene)
        }

        boardView.ignoresSiblingOrder = true

        boardView.showsFPS = true
        boardView.showsNodeCount = true

        interactor?.loadScene(request: Play.LoadGame.Request())
    }

    public override var traitCollection: UITraitCollection {
        if UIDevice.current.userInterfaceIdiom == .pad && UIDevice.current.orientation.isPortrait {
            return UITraitCollection(traitsFrom: [UITraitCollection(horizontalSizeClass: .compact), UITraitCollection(verticalSizeClass: .regular)])
        }
        return super.traitCollection
    }
}

// MARK: - BoardScene Action Delegate

extension PlayViewController: BoardSceneActionDelegate {
    func submitMove(_ point: GridPoint) {
        let request = Play.SubmitMove.Request(move: point)

        interactor?.submitMove(request: request)
    }
}

// MARK: - Display

extension PlayViewController: PlayDisplayLogic {
    func displayLoadScene(viewModel: Play.LoadGame.ViewModel) {
        boardScene.initialize(viewModel.state)
    }

    func displayUpdateGame(viewModel: Play.UpdateGame.ViewModel) {
        boardScene.render(viewModel.state)
    }

    func displayUpdateClock(viewModel: Play.UpdateGameInfo.ViewModel) {
        gameInfoView.setModel(viewModel.gameInfoViewModel)
    }
}

// MARK: Setup

private extension PlayViewController {
    func setup() {
        let viewController = self
        let interactor = PlayInteractor()
        let presenter = PlayPresenter()
        let router = PlayRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
