//
//  PlayModels.swift
//  iosgo
//
//  Created by Cheese Onhead on 6/25/17.
//  Copyright (c) 2017 Cheeseonhead. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import PromiseKit
import UIKit

enum Play {
    enum LoadGame {
        struct Request {
            var id: Int
        }

        struct Response {
            var state: GoState
            var game: Game
            var icons: (black: UIImage, white: UIImage)
        }

        struct ViewModel {
            var state: GridState
            var black: PlayerInfoView.ViewModel
            var white: PlayerInfoView.ViewModel
        }
    }

    enum UpdateGame {
        struct Response {
            var state: GoState
        }

        struct ViewModel {
            var state: GridState
        }
    }

    enum SubmitMove {
        struct Request {
            var move: GridPoint
        }
    }

    enum UpdateClock {
        struct Response {
            let clock: Clock
            let clockType: TimeControlType
        }

        struct ViewModel {
            let blackTimeStr: String
            let whiteTimeStr: String
        }
    }
}
