#!/usr/bin/env ruby
require 'colorize'
# borrowed from gitpro book http://git-scm.com/book/en/Customizing-Git-An-Example-Git-Enforced-Policy
message_file = ARGV[0]
message = File.open(message_file, "r:UTF-8", &:readline)
$regex = /^(?!#)(.*?)(\d+)/

if !$regex.match(message)
  head = File.read("./.git/HEAD")
  branch = $regex.match(head)
  if (branch && branch.length == 3)
    File.open(message_file, "w") {|f| f.write("#" + branch[2] + " | " + message) }
    exit 0
  end

  puts "Warning: Your message is missing JIRA issue tag".yellow
  exit 0
end
